### ISSUE TITLE
Weekly earnings?

### ISSUE THREAD

**Issue by emmajuliej** [matt-saenz/cpsR#21]
Hello Matt, thank you this package is really helpful.
I was wondering if you would be able to help with something. I was trying to use this package to download the weekly earnings data (variable name "PRERNWA") , but I get following error: Error: Census API request failed [400]: Bad Request
However, I am able to download other variables such as type of person, age, sex, education attainment, etc. I was wondering how I could download weekly warnings with your package? Thank you for your help!
-Emma

**Comment by matt-saenz** [comment]
@emmajuliej Hey Emma, did the above response end up resolving the issue?
